# SSH Public Key for root. This can be commented out if not required.
# Multiple entries can be provided. Proxmox will prompt for root password
# or SSH key at template deployment, this setting allows
SSH_KEY +="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Wh7yS/6uq112z+KvbYnQmam2DQrbxeaa/DsU9fBms7eo3yrAQOSj+l1h+XksWMBKTeYQczo08gCLz+5MijUg2VhrGSl4B/dIYHGRm+/yXiaICb5/76u6+jTr1m5Pk4q2FKPRbb7MOzrUobZr6zNdqg3a56V6oMdedsakEh4P/kupt6CntOM+3gGfk884Pa+1uciUDhaLYRd59EDZUb0uQIx/sKalP9JzM/5/ilQVP0Y3/tzt5DR1zIlV/X2/EYMzN7Ktg3/fd0p07bx7rYrjwpzWmaIfw0F+s2igu1yItCQsAa3S9PAAmY+PwZ+zncZDWpdwVp71/I3082yhjnwl dab_key1@nate.id.au\n"
SSH_KEY +="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaLbPkfm7OFUAujAu5LXL7H6B+71HXo+tLkB5j8De1rd42RHx4tF7lvZFCdwFuKe3KWSPoNIRBfg9qESe/DsYQcKMG2dj0GQNC5qtuhbjBOHU6pV7vNx2LVjvNDgglTVDx/eCPv8mt3fIzBBjI2uV0/MVkUpVc0XmXsyqsbqR/uapYJgvrRN5dq8xUSlG+sg8aq98YZSuWpw6mNQMyIfI7e0YbOFTWNcHwh7TYC8/qV/3dPHb3m1HH9anKd4hJkVs7rQLo+9Id6vl0k362xIUawBqlUliqbb/Y5KJDIJebQbRrWnR4c1BNplMGL1AU4rQAXdslzZ8QozjHfUs5XmMRBpFUtGirCYJ1kip25i3mqlE3mPBYTZEZ53/UYzMaKCA11tBZ3ULMzfX0cU2pkcqtiywlOBiMrlHaH5ulZevfHZbn0KXPaxB2Q7vDIT9SH5eFwqBaGoI+VrQDZFcbYV2F5t/zv5WfVGiuHEb9WSQ1++ZcBsSGHKncLSsk03M14wCt23gKUZOwn3inwR8qegvcCBuzuphmNjXpE0bQQMaU0R0sQtf3qZjlnwS6yxACNZ5RXKvqDzUFF0VEoA1CLLNjL3EnNSrhPXXRNKhsprfM428Jq3LoR9pJjzRa8nksE+0LDIwfjPZXqI9nRCTjV+Gegh350OnqtMC4XQKyZVmCOw== dab_key2@nate.id.au\n"

# Add standard packages that you would like by default on all templates
PACKAGES += sudo tcpdump traceroute

# Set this to 1 to permit root login over SSH.
# This is important if you are using Proxmox without a public SSH key, as 
# This is not a very secure configuration and the strong suggestion is to have this disabled by
# your build system as soon after the template is deployed as possible
PERMITROOT=0

# Set your local timezone (comment out for default)
TIMEZONE=Australia/Melbourne

# Rsyslogd RELP log hosts
# If this is set, we will configure rsyslog for RELP and start logging remotely at build time
# This allows us immediate visibility of new containers created via rsyslog
RELP_TARGETS += "10.10.10.10"

# Set this to 1 if you would like colourful ls output and shell prompts by default
COLOUR=1

all:

.PHONY: colour global pkgs rootpw rsyslog sshkey tz
global: colour pkgs rootpw rsyslog sshkey tz

colour:
ifneq ($(strip $(COLOUR)),)
	echo "export PS1='\[\033[36m\]\h\[\033[32m\] \w\[\033[00m\]:'" >> $(BASEDIR)/etc/environment
	echo "alias ls=\"ls -lh --color\"" >> $(BASEDIR)/etc/environment
endif

pkgs:
ifneq ($(strip $(PACKAGES)),)
	dab install $(PACKAGES)
endif

sshkey:
ifneq ($(strip $(SSH_KEY)),)
	mkdir -p $(BASEDIR)/root/.ssh
	echo $(SSH_KEY) >> $(BASEDIR)/root/.ssh/authorized_keys.tmp
	cat $(BASEDIR)/root/.ssh/authorized_keys.tmp | sed 's/^ //g' | egrep -v ^$$ > $(BASEDIR)/root/.ssh/authorized_keys
	rm -f $(BASEDIR)/root/.ssh/authorized_keys.tmp
endif

rootpw:
ifeq ($(strip $(PERMITROOT)),1)
	sed -e 's/^PermitRootLogin without-password/PermitRootLogin yes/' -i ${BASEDIR}/etc/ssh/sshd_config
endif

rsyslog:
	echo $(RELP_TARGETS)

tz:
ifneq ($(strip $(TIMEZONE)),)
	dab exec rm -rf /etc/localtime
	dab exec ln -s /usr/share/zoneinfo/$(TIMEZONE) /etc/localtime
	echo $(TIMEZONE) > $(BASEDIR)/etc/timezone
endif
