# SSH Public Key for root. This can be commented out if not required.
# Multiple entries can be provided. Proxmox will prompt for root password
# or SSH key at template deployment, this setting allows you enter a root
# password in Proxmox (which may not be usable if root password SSH is disabled)
# and then use the private keys which correspond to these keys to log in and
# do all of the initial setup
SSH_KEY +="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDq/vZSoOyTgseRtxs3woHp06uN9Jpn1K5o7Gb1YSBYZxVxURb2bQJZCT1NDIjd5G7aQjtnRx+Q1ObjcJhjC6/dq7Njs9xhWApES+P35eEz30QJ73Q8lWYMYoK3LJfZssk8KoQ5PTGnQ1sehLCxOZ++c8Tt4Um3y3+3z0guemGvcFoD1VN/KQ7PRGY4ii8pLjEQIIyW+U6xOvA4U+D8E5IT68J/Z+vQPZJlqy/l08aC83uGhYx11h557OITvzG2JhpK1xNZkAP+k+q9+S3xXXBetxWS/s9WXSfKzVA9Vf+KP1pleThtFMNG/qN1xlzXREB0tvF04Wwh6OLRrlx651uQD/1Em9TA/lWU0eDI6b5Ltgg7Gh/p+Li+U+pt8J9K7J+TjC4C4MUXNd0VYgoQndbhSrzMgn0FJQORC1OLLejC1rf3ZuarVyDAvRvd6gX+TJmSw8dzB4oi9lNearJsTEDb/4krm2Z0yATKBP5Mji8VO00/hyDg4Cc8DWHj7/hSd7EPOWfRYkByNerongWUUtTmyAYDtvzgJ4JdF7fqlZtfIn5Fp8sN/wOrkB26aSDtTqpDLAWh3EwVjl3/53wVdfGD4HErAjEr2qnDM5vLPenEqktsPNDxuAkws+Ku7MTojByLH0IpyuS0zg9mm4ZarNWRYKtb2Q+NiJkjp0xym/dm0w== dabkey1@nate.id.au\n"
SSH_KEY +="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbkvYqCZ7+8dVtVI6dIsla9QL5llL9qfHkOlF7rOZUrg35eYq8TJ7yj0dh9Uo1IEoNjz8LT+pK6G2URkTVSD9KK9CYhxDD/G6VWMQix7h6Yfwxfew+waffFxrfJu2XrlsVzEIFvXsWCX+s/5t0XBRMgOCs8tIxkFLsA+11Ldnv7GCIdDfB5bis74JNkgyoGVo8TSbiLh4yhePlWGq3J1qRqTKGM22efo4QEZ99LAdJomRPqV2kvRU+UpVmWm1VFJsJXvUZJoIRiVK7JeNfNOErOzSSiWpMiInmho/Zd3376cVbY2O+AlwrrZgmlqOprPA4MlHU/xM22WxY/WWXI0Q+SrqSFaQSY+V5nit0BIypEuvlkAMv6pcpC10sSYHbz3FH5GdEhwRVfX6nYjFZvT0IRHLzMWs3hel719Ymu6gKCKJM7ARl9Ev31C2OQUR8HZF2WQKxPp6rcG0/nITdlfiMtg3cVFSmZ141hptsEIv3dXGZMezw0Uc8Ui2LNuTc+X9bgDkG9D3Uw3EpthWgY5XtcCjTAW+x8NDeTQOy4p3DUVlFEvo0c8hqqg/Nm1iYvPKgD9eDzcag2B2RWDGFtSCk0mfjmeeH9XOeuDGhKhmp1EmAx6GtZmi2DNn7QoXyQbL6V56pFD+SvhWS0HrekcgOvCIkzRVBvwb3eKlFjPo06Q== dabkey2@nate.id.au\n"
SSH_KEY +="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHrcaS58JlhysqH89XSQIjqlGLTqJZmp7DDxAjsToic0YMQyEEj5E9vEK+Zv6GloUJ+6u5WqsTByHTpqtFO96ZbjoXL+WEI8t0KFAlxtIN2Kc4qBvLKaOlTkT2FqF7sgdQSjPw13YYRFzs7hyCfq1YehP0b583bxhOA1j/htbLBCTXHe7Jt7fyduFGr3PFobEEU2kPoKjgE7dUDlK5Pcy1AJ0vgpIpDa8A42EtbZLWhbzZKN2iMisF0G6RyDLGi712XNF6BaZ6kh0RgRnYyDePmOHQvX2xqMBZ4g85ueFEkyNqQKT8VO1tDrjqxd3k+s65XyGvFzJl4/QZO2Aqb+R8L6NYQcXr0xTvKms4r5jM1TMDOHRfddSP+wsj4a87EiEpub5fckTo6v1Abj84SyY/zNtuV5cN7OCb8g+BnyV3H1DrV/hWafSrxwqFlAPv0hNDcpkt9rFLcmnQoEEXPKEzc2ZkqfNb80tqJafUmADme7pR3t2oJ6pBnnH3G15rA4MQNhS1QEn13Gk6kQMGjOlpUVIIMdfPWBkImkSEGvB0GhfiECMN8+OpT+Dulaheg/DumfcN0r86LpF4EbWWILFdIwzTE1EZz0mrnVRrthYc0GbAR4B1sYJqX9K9+J9dRGIBitEGUcY5WxImiJWde2Q4PDqDTG6+N3vMOfg+sTJLFQ== dabkey3@nate.id.au\n"

# Add standard packages that you would like by default on all templates
PACKAGES += sudo tcpdump traceroute

# Set this to 1 to permit root login over SSH.
# This is important if you are using Proxmox without a public SSH key, as 
# This is not a very secure configuration and the strong suggestion is to have this disabled by
# your build system as soon after the template is deployed as possible
PERMITROOT=0

# Set your local timezone (comment out for default)
TIMEZONE=Australia/Melbourne

# Rsyslogd RELP log hosts
# If this is set, we will configure rsyslog for RELP and start logging remotely at build time
# This allows us immediate visibility of new containers created via rsyslog
RELP_TARGETS += "10.10.10.10"

# Set this to 1 if you would like colourful ls output and shell prompts by default
COLOUR=1

all:

.PHONY: colour global pkgs rootpw rsyslog sshkey tz
global: colour pkgs rootpw rsyslog sshkey tz

colour:
ifneq ($(strip $(COLOUR)),)
	echo "export PS1='\[\033[36m\]\h\[\033[32m\] \w\[\033[00m\]:'" >> $(BASEDIR)/etc/environment
	echo "alias ls=\"ls -lh --color\"" >> $(BASEDIR)/etc/environment
endif

pkgs:
ifneq ($(strip $(PACKAGES)),)
	dab install $(PACKAGES)
endif

sshkey:
ifneq ($(strip $(SSH_KEY)),)
	mkdir -p $(BASEDIR)/root/.ssh
	echo $(SSH_KEY) >> $(BASEDIR)/root/.ssh/authorized_keys.tmp
	cat $(BASEDIR)/root/.ssh/authorized_keys.tmp | sed 's/^ //g' | egrep -v ^$$ > $(BASEDIR)/root/.ssh/authorized_keys
	rm -f $(BASEDIR)/root/.ssh/authorized_keys.tmp
endif

rootpw:
ifeq ($(strip $(PERMITROOT)),1)
	sed -e 's/^PermitRootLogin without-password/PermitRootLogin yes/' -i ${BASEDIR}/etc/ssh/sshd_config
endif

rsyslog:
ifneq ($(strip $(RELP_TARGETS)),)
	dab install rsyslog-relp
	echo $(RELP_TARGETS)
endif

tz:
ifneq ($(strip $(TIMEZONE)),)
	dab exec rm -rf /etc/localtime
	dab exec ln -s /usr/share/zoneinfo/$(TIMEZONE) /etc/localtime
	echo $(TIMEZONE) > $(BASEDIR)/etc/timezone
endif
